name: Unit tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Run all unit tests on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.X]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: Use Yarn
        run: |
          npm i yarn -g
          yarn -v

      - name: Install Dependencies
        # All dependencies installed by lerna
        run: yarn bootstrap --registry https://registry.npmjs.org/

      - name: Run all unit tests
        run: yarn test
